# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from feditest.nodedrivers.grpc import node_pb2 as feditest_dot_nodedrivers_dot_grpc_dot_node__pb2

GRPC_GENERATED_VERSION = '1.63.0'
GRPC_VERSION = grpc.__version__
EXPECTED_ERROR_RELEASE = '1.65.0'
SCHEDULED_RELEASE_DATE = 'June 25, 2024'
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    warnings.warn(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in feditest/nodedrivers/grpc/node_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
        + f' This warning will become an error in {EXPECTED_ERROR_RELEASE},'
        + f' scheduled for release on {SCHEDULED_RELEASE_DATE}.',
        RuntimeWarning
    )


class FeditestNodeServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetActorUri = channel.unary_unary(
                '/feditest.nodedrivers.grpc.service.FeditestNodeService/GetActorUri',
                request_serializer=feditest_dot_nodedrivers_dot_grpc_dot_node__pb2.ActorUriRequest.SerializeToString,
                response_deserializer=feditest_dot_nodedrivers_dot_grpc_dot_node__pb2.ActorUriReply.FromString,
                _registered_method=True)
        self.GetActorFollowerUri = channel.unary_unary(
                '/feditest.nodedrivers.grpc.service.FeditestNodeService/GetActorFollowerUri',
                request_serializer=feditest_dot_nodedrivers_dot_grpc_dot_node__pb2.ActorFollowersUriRequest.SerializeToString,
                response_deserializer=feditest_dot_nodedrivers_dot_grpc_dot_node__pb2.ActorFollowersUriReply.FromString,
                _registered_method=True)
        self.GetActorFollowingUri = channel.unary_unary(
                '/feditest.nodedrivers.grpc.service.FeditestNodeService/GetActorFollowingUri',
                request_serializer=feditest_dot_nodedrivers_dot_grpc_dot_node__pb2.ActorFollowingUriRequest.SerializeToString,
                response_deserializer=feditest_dot_nodedrivers_dot_grpc_dot_node__pb2.ActorFollowingUriReply.FromString,
                _registered_method=True)
        self.CreateObject = channel.unary_unary(
                '/feditest.nodedrivers.grpc.service.FeditestNodeService/CreateObject',
                request_serializer=feditest_dot_nodedrivers_dot_grpc_dot_node__pb2.CreateObjectRequest.SerializeToString,
                response_deserializer=feditest_dot_nodedrivers_dot_grpc_dot_node__pb2.CreateObjectReply.FromString,
                _registered_method=True)
        self.WaitFprInboxObject = channel.unary_unary(
                '/feditest.nodedrivers.grpc.service.FeditestNodeService/WaitFprInboxObject',
                request_serializer=feditest_dot_nodedrivers_dot_grpc_dot_node__pb2.WaitForInboxObjectRequest.SerializeToString,
                response_deserializer=feditest_dot_nodedrivers_dot_grpc_dot_node__pb2.WaitForInboxObjectReply.FromString,
                _registered_method=True)
        self.AnnounceObject = channel.unary_unary(
                '/feditest.nodedrivers.grpc.service.FeditestNodeService/AnnounceObject',
                request_serializer=feditest_dot_nodedrivers_dot_grpc_dot_node__pb2.AnnounceObjectRequest.SerializeToString,
                response_deserializer=feditest_dot_nodedrivers_dot_grpc_dot_node__pb2.AnnounceObjectReply.FromString,
                _registered_method=True)
        self.ReplyToObject = channel.unary_unary(
                '/feditest.nodedrivers.grpc.service.FeditestNodeService/ReplyToObject',
                request_serializer=feditest_dot_nodedrivers_dot_grpc_dot_node__pb2.ReplyToObjectRequest.SerializeToString,
                response_deserializer=feditest_dot_nodedrivers_dot_grpc_dot_node__pb2.ReplyToObjectReply.FromString,
                _registered_method=True)
        self.FollowActor = channel.unary_unary(
                '/feditest.nodedrivers.grpc.service.FeditestNodeService/FollowActor',
                request_serializer=feditest_dot_nodedrivers_dot_grpc_dot_node__pb2.FollowActorRequest.SerializeToString,
                response_deserializer=feditest_dot_nodedrivers_dot_grpc_dot_node__pb2.FollowActorReply.FromString,
                _registered_method=True)
        self.CollectionContains = channel.unary_unary(
                '/feditest.nodedrivers.grpc.service.FeditestNodeService/CollectionContains',
                request_serializer=feditest_dot_nodedrivers_dot_grpc_dot_node__pb2.CollectionContainsRequest.SerializeToString,
                response_deserializer=feditest_dot_nodedrivers_dot_grpc_dot_node__pb2.CollectionContainsReply.FromString,
                _registered_method=True)


class FeditestNodeServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetActorUri(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetActorFollowerUri(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetActorFollowingUri(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateObject(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def WaitFprInboxObject(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AnnounceObject(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReplyToObject(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FollowActor(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CollectionContains(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FeditestNodeServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetActorUri': grpc.unary_unary_rpc_method_handler(
                    servicer.GetActorUri,
                    request_deserializer=feditest_dot_nodedrivers_dot_grpc_dot_node__pb2.ActorUriRequest.FromString,
                    response_serializer=feditest_dot_nodedrivers_dot_grpc_dot_node__pb2.ActorUriReply.SerializeToString,
            ),
            'GetActorFollowerUri': grpc.unary_unary_rpc_method_handler(
                    servicer.GetActorFollowerUri,
                    request_deserializer=feditest_dot_nodedrivers_dot_grpc_dot_node__pb2.ActorFollowersUriRequest.FromString,
                    response_serializer=feditest_dot_nodedrivers_dot_grpc_dot_node__pb2.ActorFollowersUriReply.SerializeToString,
            ),
            'GetActorFollowingUri': grpc.unary_unary_rpc_method_handler(
                    servicer.GetActorFollowingUri,
                    request_deserializer=feditest_dot_nodedrivers_dot_grpc_dot_node__pb2.ActorFollowingUriRequest.FromString,
                    response_serializer=feditest_dot_nodedrivers_dot_grpc_dot_node__pb2.ActorFollowingUriReply.SerializeToString,
            ),
            'CreateObject': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateObject,
                    request_deserializer=feditest_dot_nodedrivers_dot_grpc_dot_node__pb2.CreateObjectRequest.FromString,
                    response_serializer=feditest_dot_nodedrivers_dot_grpc_dot_node__pb2.CreateObjectReply.SerializeToString,
            ),
            'WaitFprInboxObject': grpc.unary_unary_rpc_method_handler(
                    servicer.WaitFprInboxObject,
                    request_deserializer=feditest_dot_nodedrivers_dot_grpc_dot_node__pb2.WaitForInboxObjectRequest.FromString,
                    response_serializer=feditest_dot_nodedrivers_dot_grpc_dot_node__pb2.WaitForInboxObjectReply.SerializeToString,
            ),
            'AnnounceObject': grpc.unary_unary_rpc_method_handler(
                    servicer.AnnounceObject,
                    request_deserializer=feditest_dot_nodedrivers_dot_grpc_dot_node__pb2.AnnounceObjectRequest.FromString,
                    response_serializer=feditest_dot_nodedrivers_dot_grpc_dot_node__pb2.AnnounceObjectReply.SerializeToString,
            ),
            'ReplyToObject': grpc.unary_unary_rpc_method_handler(
                    servicer.ReplyToObject,
                    request_deserializer=feditest_dot_nodedrivers_dot_grpc_dot_node__pb2.ReplyToObjectRequest.FromString,
                    response_serializer=feditest_dot_nodedrivers_dot_grpc_dot_node__pb2.ReplyToObjectReply.SerializeToString,
            ),
            'FollowActor': grpc.unary_unary_rpc_method_handler(
                    servicer.FollowActor,
                    request_deserializer=feditest_dot_nodedrivers_dot_grpc_dot_node__pb2.FollowActorRequest.FromString,
                    response_serializer=feditest_dot_nodedrivers_dot_grpc_dot_node__pb2.FollowActorReply.SerializeToString,
            ),
            'CollectionContains': grpc.unary_unary_rpc_method_handler(
                    servicer.CollectionContains,
                    request_deserializer=feditest_dot_nodedrivers_dot_grpc_dot_node__pb2.CollectionContainsRequest.FromString,
                    response_serializer=feditest_dot_nodedrivers_dot_grpc_dot_node__pb2.CollectionContainsReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'feditest.nodedrivers.grpc.service.FeditestNodeService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class FeditestNodeService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetActorUri(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/feditest.nodedrivers.grpc.service.FeditestNodeService/GetActorUri',
            feditest_dot_nodedrivers_dot_grpc_dot_node__pb2.ActorUriRequest.SerializeToString,
            feditest_dot_nodedrivers_dot_grpc_dot_node__pb2.ActorUriReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetActorFollowerUri(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/feditest.nodedrivers.grpc.service.FeditestNodeService/GetActorFollowerUri',
            feditest_dot_nodedrivers_dot_grpc_dot_node__pb2.ActorFollowersUriRequest.SerializeToString,
            feditest_dot_nodedrivers_dot_grpc_dot_node__pb2.ActorFollowersUriReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetActorFollowingUri(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/feditest.nodedrivers.grpc.service.FeditestNodeService/GetActorFollowingUri',
            feditest_dot_nodedrivers_dot_grpc_dot_node__pb2.ActorFollowingUriRequest.SerializeToString,
            feditest_dot_nodedrivers_dot_grpc_dot_node__pb2.ActorFollowingUriReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateObject(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/feditest.nodedrivers.grpc.service.FeditestNodeService/CreateObject',
            feditest_dot_nodedrivers_dot_grpc_dot_node__pb2.CreateObjectRequest.SerializeToString,
            feditest_dot_nodedrivers_dot_grpc_dot_node__pb2.CreateObjectReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def WaitFprInboxObject(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/feditest.nodedrivers.grpc.service.FeditestNodeService/WaitFprInboxObject',
            feditest_dot_nodedrivers_dot_grpc_dot_node__pb2.WaitForInboxObjectRequest.SerializeToString,
            feditest_dot_nodedrivers_dot_grpc_dot_node__pb2.WaitForInboxObjectReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AnnounceObject(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/feditest.nodedrivers.grpc.service.FeditestNodeService/AnnounceObject',
            feditest_dot_nodedrivers_dot_grpc_dot_node__pb2.AnnounceObjectRequest.SerializeToString,
            feditest_dot_nodedrivers_dot_grpc_dot_node__pb2.AnnounceObjectReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReplyToObject(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/feditest.nodedrivers.grpc.service.FeditestNodeService/ReplyToObject',
            feditest_dot_nodedrivers_dot_grpc_dot_node__pb2.ReplyToObjectRequest.SerializeToString,
            feditest_dot_nodedrivers_dot_grpc_dot_node__pb2.ReplyToObjectReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def FollowActor(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/feditest.nodedrivers.grpc.service.FeditestNodeService/FollowActor',
            feditest_dot_nodedrivers_dot_grpc_dot_node__pb2.FollowActorRequest.SerializeToString,
            feditest_dot_nodedrivers_dot_grpc_dot_node__pb2.FollowActorReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CollectionContains(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/feditest.nodedrivers.grpc.service.FeditestNodeService/CollectionContains',
            feditest_dot_nodedrivers_dot_grpc_dot_node__pb2.CollectionContainsRequest.SerializeToString,
            feditest_dot_nodedrivers_dot_grpc_dot_node__pb2.CollectionContainsReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
